FROM python:3.11-slim
WORKDIR /app

# Install system deps for building libraries (like scikit-learn, implicit, etc.)
RUN apt-get update && apt-get install -y --no-install-recommends gcc g++ && \
    rm -rf /var/lib/apt/lists/*

# Copy only the requirements to cache the dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
