FROM nginx:alpine
COPY nginx.conf.template /nginx.conf.template
EXPOSE 80
# envsubst replaces ${USER_JOB_HOST} and ${SWIPE_MATCH_HOST} at startup
CMD ["/bin/sh", "-c", "envsubst '${USER_JOB_HOST} ${SWIPE_MATCH_HOST}' < /nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"]
