FROM nginx:alpine
COPY nginx.conf.template /nginx.conf.template
EXPOSE 80
# envsubst replaces listed variables at startup
CMD ["/bin/sh", "-c", "envsubst '${USER_JOB_HOST} ${SWIPE_MATCH_HOST} ${COVER_LETTER_HOST}' < /nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"]
