spring.application.name=swipe-match-service
server.port=8082

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}

spring.data.mongodb.uri=mongodb+srv://jumble_app_user:test123@jumble.ewhoayr.mongodb.net/jumbledb?retryWrites=true&w=majority&appName=JUMBLE

logging.level.com.jumble.swipematch=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG
