spring.application.name=swipe-match-service
server.port=8080

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.cluster.nodes=${REDIS_CLUSTER_NODES:}
spring.data.redis.ssl.enabled=${REDIS_SSL:false}
spring.data.redis.password=${REDIS_PASSWORD:}

spring.data.mongodb.uri=${MONGO_URI:mongodb+srv://jumble_app_user:test123@jumble.ewhoayr.mongodb.net/jumbledb?retryWrites=true&w=majority&appName=JUMBLE}

logging.level.com.jumble.swipematch=INFO
logging.level.org.springframework.data.mongodb=INFO
