ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# Set the working directory in the container
WORKDIR /app

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 8000

# Command to run the application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
